myblog/models/post.py
from myblog import db
from datetime import datetime


# Crear el modelo de tabla que se transfiere a la base de datos
class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    # Relaciónar la tabla post a la de users en su columna id
    author = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    title = db.Column(db.String(50))
    content = db.Column(db.Text)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, author, title, content):
        # Argumentos necesarios para la creación de la instancia
        self.author = author
        self.title = title
        self.content = content

    def __repr__(self):
        return f'Post: {self.title}'

myblog/models/user.py
from myblog import db


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.Text)

    def __init__(self,username,password):
        self.username = username
        self.password = password

    def __repr__(self):
        return f'User: {self.username}'

myblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# Crear la app
app = Flask(__name__)

# Configurar la app en producción o desarrollo
app.config.from_object('config.DevelopmentConfig')

# Relación con base de datos
db = SQLAlchemy(app)

'''
Importar los módulos y paquetes en manera ordenada para
no encontrar errores de dependencia circular'''

from myblog.views.auth import auth
app.register_blueprint(auth)

from myblog.views.blog import blog
app.register_blueprint(blog)


with app.app_context():
    db.create_all()

myblog/views/__init__.py
from .auth import auth

myblog/views/auth.py
import functools
from os import error
from flask import (render_template, Blueprint,
                   flash, g, redirect, request,
                   session,url_for)
'''
render_template: se utiliza para redirigir templates
Blueprint: se utiliza para registrar las vistas en la aplicación
flash: se utiliza para enviar mensajes cuando ocurren errores
g: se utiliza para capturar el usuario que ha iniciado sesión
redirect: se utiliza para redirection a una nueva ruta
request: se utiliza para capturar las peticiones del cliente
session: se utiliza para realizar consultas a la base de datos
url_for: se utiliza para trabajar con las rutas de manera dinámica
'''

from werkzeug.security import check_password_hash,generate_password_hash
from myblog import db


auth = Blueprint('auth', __name__, url_prefix='/auth')

from myblog.models.user import User

# Registrar usuario
@auth.route('/register', methods=['GET','POST'])
def register():
    # Con el decorador .rout asignamos el nombre register;
    # Con la petición auth/register devolvemos la función que decora
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User(username=username, password=generate_password_hash(password))
        # Consultar presencia de errores
        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere la contraseña'
        # Consultar la tabla del modelo User
        user_name = User.query.filter_by(username=username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            error = f'El usuario {username} ya está registrado'
        flash(error)
        # Con el tag get_flashed_messages() llamo los errores en los templates
    return render_template('auth/register.html')


# Iniciar sesión usuario
@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User(username=username, password=generate_password_hash(password))
        error = None
        user = User.query.filter_by(username=username).first()
        if user==None:
            error = 'El usuario no está registrado'
        elif not check_password_hash(user.password, password):
            error = 'La contraseña es incorrecta'

        if error is None:
            session.clear()
            session['user_id']=user.id
            return redirect(url_for('blog.index'))
        flash(error)
    return render_template('auth/login.html')


# Verificar login
# Con el siguiente decorador se llama la función para cualquier solicitud de la app
@auth.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        # Con g almaceno el objeto para llamarlo sin buscarlo cada vez
        g.user = None
    else:
        g.user = User.query.get_or_404(user_id)


# Cerrar sesión
@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('blog.index'))


# Inicio sesión obligatorio
def login_required(view):
    '''El decorador tiene la capacidad de envolver la función
    sin perder las informaciones, que contiene de la función original,
    para utilizarlas otra vez'''
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            # si g.user no contiene datos redirigir a login
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

myblog/views/blog.py
from flask import(
    render_template,Blueprint,flash,
    g, request, redirect, url_for
    )
from werkzeug.exceptions import abort
from myblog.models.post import Post
from myblog.models.user import User
from myblog.views.auth import login_required
from myblog import db

blog = Blueprint('blog',__name__)


# obtener el usuario
def get_user(id):
    user = User.query.get_or_404(id)
    return user


# Obtener publicaciones
@blog.route('/')
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/index.html', posts=posts, get_user=get_user)


# Crear publicación
@blog.route('/blog/create', methods=['GET','POST'])#sigue la ruta /auth
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')

        post = Post(g.user.id, title=title,content=content)
        error = None
        if not title:
            error = 'Se requiere un titulo'
        elif not content:
            error = 'Se requiere el texto'
        elif error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        flash(error)
    return render_template('blog/create.html')


# obtener post
def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe')

    if check_author and post.author!=g.user.id:
        abort(404)
    return post

# Editar publicación
@blog.route('/blog/update/<int:id>', methods=['GET','POST'])#sigue la ruta /auth
@login_required
def update(id):

    post = get_post(id)

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.content = request.form.get('content')

        error = None
        if not post.title:
            error = 'Se requiere un titulo'
        elif not post.content:
            error = 'Se requiere el texto'
        elif error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        flash(error)
    return render_template('blog/update.html', post=post)


# Eliminar un post
@blog.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('blog.index'))

myblog/templates/base.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/blog.ico') }}" type="image/x-icon">

    <title>{% block title %}{% endblock %}-My Blog</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/styles.css') }}">

</head>
<body>
    <header class="header">
        <div class="nav">
            <div>
                <a href="{{ url_for('blog.index') }}">
                    <h1>My Blog</h1>
                </a>
            </div>
                <nav>
                    {% if g.user %}
                    <img src="{{ url_for ('static', filename='img/usuario.ico') }}">
                    <span>{{ g.user.username }}</span>
                    <a href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
                    {% else %}
                    <a href="{{ url_for('auth.register') }}">Registrar usuario</a>
                    <a href="{{ url_for('auth.login') }}">Iniciar sesión</a>
                    {% endif %}
                </nav>
        </div>
    </header>
    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>
            {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}
            {% block content %}{% endblock %}
        </div>
    </section>
</body>
</html>

myblog/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Crear una publicación{% endblock %}</h2>
{% endblock %}

{% block content %}

    <form method="POST">
        <label>Título</label>
        <input type="text" name="title" id="username" required>

        <label for="body">Contenido</label>
        <textarea name="content" id="body" required rows="10"></textarea>

        <input type="submit" value="Guardar">
    </form>


{% endblock %}

myblog/templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Publicaciónes{% endblock %}</h2>
    <div class="crud">
        {% if g.user %}
        <a href="{{ url_for('blog.create') }}">Nueva Publicación</a>
        {% endif %}
    </div>

{% endblock %}

{% block content %}

    {% for post in posts %}
        <article>
            <header>
                <div>
                    <h1>{{ post.title }}</h1>
                    <div class="about">
                        Publicado por {{ get_user(post.author).username }}
                        el {{ post.created }}
                    </div>
                </div>
                <div class="crud">
                    {% if g.user.id == post.author %}
                        <a href="{{ url_for('blog.update', id=post.id) }}">Editar</a>
                        <a href="{{ url_for('blog.delete', id=post.id) }}">Eliminar</a>
                    {% endif %}
                </div>

            </header>
            <div>
                <p>{{ post.content }}</p>
            </div>
        </article>


    {% endfor %}

{% endblock %}

myblog/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Actualizar una publicación{% endblock %}</h2>
{% endblock %}

{% block content %}

    <form method="POST">
        <label>Título</label>
        <input type="text" name="title" id="username" value="{{ post.title }}" required>

        <label for="body">Contenido</label>
        <textarea name="content" id="body" required rows="10">{{ post.content }}</textarea>

        <input type="submit" value="Guardar">
    </form>


{% endblock %}